require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/approvals/**/*'
    - 'debug.rb'
    - 'dev/**/*'

# Allow `set_compline_vars` here, it is more readable
Naming/AccessorMethodName:
  Exclude:
    - 'lib/completely/tester.rb'

# The `bounce` method here is more readable without this cop
Style/GuardClause:
  Exclude:
    - 'lib/completely/commands/install.rb'