require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop: rentacop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/approvals/**/*'
    - 'debug.rb'
    - 'dev/**/*'

# Allow `set_compline_vars` here, it is more readable
Naming/AccessorMethodName:
  Exclude:
    - 'lib/completely/tester.rb'

# Allow long lines in specs and commands
Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/completely/commands/**/*'

# Allow `before :all` and `after :all`
RSpec/BeforeAfterAll:
  Enabled: false

# Allow unnamed `subject`
RSpec/NamedSubject:
  Enabled: false

# Allow `describe` with arbitrary text in some cases
RSpec/DescribeClass:
  Exclude:
    - spec/completely/bin_spec.rb
    - spec/completely/integration_spec.rb
    - spec/completely/zsh_spec.rb

# Allow multiple expectations per block
RSpec/MultipleExpectations:
  Max: 3