# cli completion                                           -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_cli_completions() {
  local cur comp_line
  _init_completion -s || return
  cur=${COMP_WORDS[COMP_CWORD]}
  comp_line="${COMP_WORDS[@]:1}"

  case "$comp_line" in
    'command childcommand'*) COMPREPLY=($(compgen -W "--quiet --verbose -q -v" -- "$cur")) ;;
    'command subcommand'*) COMPREPLY=($(compgen -W "--force --quiet" -- "$cur")) ;;
    'command'*) COMPREPLY=($(compgen -W "subcommand childcommand" -- "$cur")) ;;
    ''*) COMPREPLY=($(compgen -W "--help --version command conquer" -- "$cur")) ;;
  esac
} &&
complete -F _cli_completions cli

# ex: filetype=sh
