#!/usr/bin/env bash
if [[ -n $ZSH_VERSION ]]; then
  autoload -U +X bashcompinit && bashcompinit
  autoload -U +X compinit && compinit
fi

# === COMPLETION SCRIPT START ===

source "<path removed>"

# === COMPLETION SCRIPT END ===

COMP_WORDS=( cli co )
COMP_LINE="cli co"
COMP_POINT=${#COMP_LINE}
COMP_CWORD=1

_cli_completions
for suggestion in "${COMPREPLY[@]}"; do
  echo "$suggestion"
done

